apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncareer
  namespace: ncareer
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: ncareer
  template:
    metadata:
      labels:
        app: ncareer
    spec:
      containers:
        - name: ncareer
          image: leosunghojung/ncareer:64bc80d
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
